name: B

on: 
  push:
    branches:
      - main

jobs:
  ci-reuse:
    uses: ./.github/workflows/a.yml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo B >> a.txt
          cat a.txt
